# fly.toml app configuration file generated for ai-agent-chatbot on 2025-01-21T21:45:13+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-agent-chatbot'
primary_region = 'sin'

[build]

[env]
  PORT = '3000'
  SCOPES = 'write_products'
  SHOPIFY_API_KEY = '7d9f678eb2e5039a486f9eeaf2339260'
  SHOPIFY_APP_URL = 'https://ai-agent-chatbot.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
