# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bf1972db87048d4e7b17c699e33adaf5"
application_url = "https://c634-171-225-185-27.ngrok-free.app"
embedded = true
name = "ai-agent-chatbot-dev"
handle = "ai-agent-chatbot-dev"

[build]
include_config_on_deploy = true
dev_store_url = "dev-store-of-mike.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://c634-171-225-185-27.ngrok-free.app/auth/callback",
  "https://c634-171-225-185-27.ngrok-free.app/auth/shopify/callback",
  "https://c634-171-225-185-27.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
