# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7d9f678eb2e5039a486f9eeaf2339260"
application_url = "https://ai-agent-chatbot.fly.dev"
embedded = true
name = "ai-agent-chatbot"
handle = "ai-agent-chatbot"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-store-of-mike.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ai-agent-chatbot.fly.dev/auth/callback",
  "https://ai-agent-chatbot.fly.dev/auth/shopify/callback",
  "https://ai-agent-chatbot.fly.dev/api/auth/callback"
]

[pos]
embedded = false
